image: alpine:latest
before_script: |
  apk update
  apk add git
pages:
  stage: deploy
  script: |
    mkdir -p ./public
    cd ./public
    git clone --depth 1 https://gitlab.com/octospacc/Narratika
    mv ../TheQuestion ./TheQuestion
  artifacts:
    paths:
    - public
  only:
  - examples
